title: Intersection Chicago
email: support@humanlibrarychicago.org
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://intersectionchicago.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: :compressed